### ISSUE TITLE
update modules

### ISSUE THREAD

**Issue by serapath** [serapath/codecamping#1]
## `@todo`
* [ ] rename https://github.com/wizardamigos/wizardamigos-codecamp to `wizardamigos-codecamping`
* [ ] make a wizardamigos theme and add it to that module
* [ ] use it in https://github.com/wizardamigos/codecamp-company
* [ ] use it in https://github.com/wizardamigos/codecamp-blockchain

---
